### ISSUE TITLE
Support for reading Publisher Purposes Consent String

### ISSUE THREAD

**Issue by prayashm** [prebid/go-gdpr#18]
I want to check if anyone is working on this.
Otherwise I would want to pick this up.

Going through [these](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#publisher-purposes-consent-string-format-) documentation.
Any other pointers to get this done would be helpful.

**Comment by hhhjort** [comment]
I am not sure what is still missing on this point, but there is not much active work on it currently. Can you describe what exactly you want to extract from the consent string? I suspect that it may be a matter not fully understanding what the library currently provides rather than a section of consent not being parsed. If we are missing some functionality, we would be happy to have a PR submitted to provide it.

**Comment by prayashm** [comment]
in [TCFv2](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-information-is-stored-in-a-tc-string), a publisher purposes consent specifies how can the 1st Party publisher use the data.

Let me close this, it was a while ago and we do not need this feature anymore.
